### ISSUE TITLE
Error when using microservices + mongodb + UAA + spring web flux

### ISSUE THREAD

**Issue by diegozup** [jhipster/jhipster-kotlin#283]
## Overview of the issue
I'm using khipster to create microservices with mongodb + Oauth2 + spring web flux

## Reproduce the error
Just using the following steps below is enough.

## KHipster Version(s)
v1.12.1

-   [x] Checking this box is mandatory (this is just to show you read everything)

## Error

**My So**:
- Ubuntu LTS: 20.04 64bits
- Node version: v14.17.0
- Java version: 11
- I'm running the commands below in a container as per the tutorial

```bash
[pc]:~/jh-generator-kotlin/service $ docker run -it --rm -v $PWD:/home/khipster/app jhipster-generator-kotlin
INFO! Using JHipster version installed globally
INFO! No custom sharedOptions found within blueprint: generator-jhipster-kotlin at /usr/local/lib/node_modules/generator-jhipster-kotlin
INFO! No custom commands found within blueprint: generator-jhipster-kotlin at /usr/local/lib/node_modules/generator-jhipster-kotlin
     info Using blueprint generator-jhipster-kotlin for app subgenerator
WARNING! Priority composing is missing for generator jhipster-kotlin:app. Merging into default priority.


 ██╗  ██╗ ██╗   ██╗ ████████╗ ███████╗   ██████╗ ████████╗ ████████╗ ███████╗
 ██║ ██╔╝ ██║   ██║ ╚══██╔══╝ ██╔═══██╗ ██╔════╝ ╚══██╔══╝ ██╔═════╝ ██╔═══██╗
 █████╔╝  ████████║    ██║    ███████╔╝ ╚█████╗     ██║    ██████╗   ███████╔╝
 ██╔═██╗  ██╔═══██║    ██║    ██╔════╝   ╚═══██╗    ██║    ██╔═══╝   ██╔══██║
 ██║  ██╗ ██║   ██║ ████████╗ ██║       ██████╔╝    ██║    ████████╗ ██║  ╚██╗
 ╚═╝  ╚═╝ ╚═╝   ╚═╝ ╚═══════╝ ╚═╝       ╚═════╝     ╚═╝    ╚═══════╝ ╚═╝   ╚═╝

Welcome to KHipster v1.12.1
Application files will be generated in folder: /home/khipster/app
 _______________________________________________________________________________________________________________

  Documentation for creating an application is at https://www.jhipster.tech/creating-an-app/
  If you find KHipster useful, consider sponsoring the our parent project at https://opencollective.com/generator-jhipster
 _______________________________________________________________________________________________________________

WARNING! Java is not found on your computer.
WARNING! git is not found on your computer.

? May JHipster anonymously report usage statistics to improve the tool over time? No
? Which *type* of application would you like to create? Microservice application
? What is the base name of your application? app
     info Using blueprint generator-jhipster-kotlin for server subgenerator
WARNING! Priority composing is missing for generator jhipster-kotlin:server. Merging into default priority.
WARNING! Priority loading is missing for generator jhipster-kotlin:server. Merging into default priority.
WARNING! Priority preparing is missing for generator jhipster-kotlin:server. Merging into default priority.
? Do you want to make it reactive with Spring WebFlux? Yes
? As you are running in a microservice architecture, on which port would like your server to run? It should be unique to avoid p
ort conflicts. 8081
? What is your default Java package name? com.mycompany.myapp
? Which service discovery server do you want to use? Consul
? Which *type* of authentication would you like to use? OAuth 2.0 / OIDC Authentication (stateful, works with Keycloak and Okta)


? Which *type* of database would you like to use? MongoDB
? Would you like to use Maven or Gradle for building the backend? Maven
? Which other technologies would you like to use? 
? Would you like to enable internationalization support? No
? Please choose the native language of the application English
? Besides JUnit and Jest, which testing frameworks would you like to use? 
? Would you like to install other generators from the JHipster Marketplace? No
/bin/sh: 1: keytool: not found
WARNING! 
Failed to create a KeyStore with 'keytool'
ERROR! /usr/local/lib/node_modules/generator-jhipster-kotlin/generators/server/templates/src/main/kotlin/package/domain/User.kt.ejs:100
    98| import java.time.Instant
    99| import java.util.Locale
 >> 100| <%_ if (user.primaryKey.type === 'UUID') { _%>
    101| import java.util.UUID
    102| <%_ } _%>
    103| 

Cannot read property 'primaryKey' of undefined
TypeError: /usr/local/lib/node_modules/generator-jhipster-kotlin/generators/server/templates/src/main/kotlin/package/domain/User.kt.ejs:100
    98| import java.time.Instant
    99| import java.util.Locale
 >> 100| <%_ if (user.primaryKey.type === 'UUID') { _%>
    101| import java.util.UUID
    102| <%_ } _%>
    103| 

Cannot read property 'primaryKey' of undefined
    at module.exports.eval (eval at compile (/usr/local/lib/node_modules/generator-jhipster-kotlin/node_modules/ejs/lib/ejs.js:662:12), <anonymous>:83:17)
    at User.kt (/usr/local/lib/node_modules/generator-jhipster-kotlin/node_modules/ejs/lib/ejs.js:692:17)
    at /usr/local/lib/node_modules/generator-jhipster-kotlin/node_modules/ejs/lib/ejs.js:258:40
    at new Promise (<anonymous>)
    at tryHandleCache (/usr/local/lib/node_modules/generator-jhipster-kotlin/node_modules/ejs/lib/ejs.js:256:14)
    at Object.exports.renderFile (/usr/local/lib/node_modules/generator-jhipster-kotlin/node_modules/ejs/lib/ejs.js:489:10)
    at Object.renderContent (/usr/local/lib/node_modules/generator-jhipster-kotlin/node_modules/generator-jhipster/generators/utils.js:286:23)
    at module.exports.template (/usr/local/lib/node_modules/generator-jhipster-kotlin/node_modules/generator-jhipster/generators/generator-base-private.js:758:26)
    at /usr/local/lib/node_modules/generator-jhipster-kotlin/node_modules/generator-jhipster/generators/generator-base.js:2222:47
    at Array.map (<anonymous>) {
  path: '/usr/local/lib/node_modules/generator-jhipster-kotlin/generators/server/templates/src/main/kotlin/package/domain/User.kt.ejs'
}
```
## Error image

![image](https://user-images.githubusercontent.com/73549129/120413636-0c2bac00-c32f-11eb-9199-6a2d55309677.png)

**Comment by sendilkumarn** [comment]
@diegozup  I cannot replicate the above issue. Can you share the `.yo-rc.json` file?

**Comment by sendilkumarn** [comment]
Please feel free to re-open the issue if you still have it in the main branch.
