### ISSUE TITLE
A newbie cannot make it run

### ISSUE THREAD

**Issue by danaki** [jhipster/jhipster-kotlin#325]
According to documentation:

```
npm install -g generator-jhipster-kotlin
```

```
(base) {1:03}~/work/jh/kt-app ➭ khipster --version
node:internal/modules/cjs/loader:488
      throw e;
      ^

Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: Package subpath './cli/utils' is not defined by "exports" in /usr/local/lib/node_modules/generator-jhipster-kotlin/node_modules/generator-jhipster/package.json
    at new NodeError (node:internal/errors:371:5)
    at throwExportsNotFound (node:internal/modules/esm/resolve:429:9)
    at packageExportsResolve (node:internal/modules/esm/resolve:705:3)
    at resolveExports (node:internal/modules/cjs/loader:482:36)
    at Function.Module._findPath (node:internal/modules/cjs/loader:522:31)
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:919:27)
    at Function.Module._load (node:internal/modules/cjs/loader:778:27)
    at Module.require (node:internal/modules/cjs/loader:999:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/generator-jhipster-kotlin/cli/khipster.js:22:20) {
  code: 'ERR_PACKAGE_PATH_NOT_EXPORTED'
}

Node.js v17.5.0
```

```
(base) {1:05}~/work/jh/kt-app ➭ jhipster --blueprint kotlin
INFO! Using JHipster version installed globally
INFO! No custom sharedOptions found within blueprint: generator-jhipster-kotlin at /usr/local/lib/node_modules/generator-jhipster-kotlin
INFO! No custom commands found within blueprint: generator-jhipster-kotlin at /usr/local/lib/node_modules/generator-jhipster-kotlin
ERROR! Package subpath './generators/app' is not defined by "exports" in /usr/local/lib/node_modules/generator-jhipster-kotlin/node_modules/generator-jhipster/package.json
Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: Package subpath './generators/app' is not defined by "exports" in /usr/local/lib/node_modules/generator-jhipster-kotlin/node_modules/generator-jhipster/package.json
    at new NodeError (node:internal/errors:371:5)
    at throwExportsNotFound (node:internal/modules/esm/resolve:429:9)
    at packageExportsResolve (node:internal/modules/esm/resolve:705:3)
    at resolveExports (node:internal/modules/cjs/loader:482:36)
    at Function.Module._findPath (node:internal/modules/cjs/loader:522:31)
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:919:27)
    at Function.Module._load (node:internal/modules/cjs/loader:778:27)
    at Module.require (node:internal/modules/cjs/loader:999:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/generator-jhipster-kotlin/generators/app/index.js:20:23) {
  code: 'ERR_PACKAGE_PATH_NOT_EXPORTED'
}
```

**Comment by mraible** [comment]
Does it work with Node 16?

**Comment by liefra** [comment]
@danaki: I just got the same error and it worked for me after switching to Node 16

**Comment by sendilkumarn** [comment]
@danaki  closing this for now, please feel free to reopen if you face the same error after switching to Node 16.

**Comment by awikatchikaen** [comment]
I have the problem with node 18.16 (lastest LTS), and i don’t want nor know how to downgrade node.
