### ISSUE TITLE
jhipster-native compatible 

### ISSUE THREAD

**Issue by bahag-chaurasiak** [jhipster/jhipster-kotlin#326]
## Overview of the issue

I have tried to use jhipster-native with --blueprint kotlin and run into compatibility issue 

ERROR! The installed generator-jhipster-native blueprint targets JHipster v7.7.0 and is not compatible with this JHipster version. Either update the blueprint or JHipster. You can also disable this check using --skip-checks at your own risk
Error: The installed generator-jhipster-native blueprint targets JHipster v7.7.0 and is not compatible with this JHipster version. Either update the blueprint or JHipster. You can also disable this check using --skip-checks at your own risk
    at module.exports.error (/Users/krashna/.nvm/versions/node/v16.6.1/lib/node_modules/generator-jhipster-kotlin/node_modules/generator-jhipster/generators/generator-base.js:1827:11)
    at module.exports._checkJHipsterBlueprintVersion (/Users/krashna/.nvm/versions/node/v16.6.1/lib/node_modules/generator-jhipster-kotlin/node_modules/generator-jhipster/generators/generator-base-blueprint.js:427:14)
    at /Users/krashna/.nvm/versions/node/v16.6.1/lib/node_modules/generator-jhipster-kotlin/node_modules/generator-jhipster/generators/app/index.js:327:18
    at Array.forEach (<anonymous>)
    at module.exports.validateBlueprint (/Users/krashna/.nvm/versions/node/v16.6.1/lib/node_modules/generator-jhipster-kotlin/node_modules/generator-jhipster/generators/app/index.js:326:42)
    at Object.<anonymous> (/Users/krashna/.nvm/versions/node/v16.6.1/lib/node_modules/generator-jhipster-kotlin/node_modules/yeoman-generator/lib/index.js:1024:25)
    at /Users/krashna/.nvm/versions/node/v16.6.1/lib/node_modules/generator-jhipster-kotlin/node_modules/run-async/index.js:49:25
    at new Promise (<anonymous>)
    at /Users/krashna/.nvm/versions/node/v16.6.1/lib/node_modules/generator-jhipster-kotlin/node_modules/run-async/index.js:26:19
    at runLoop.add.once.once (/Users/krashna/.nvm/versions/node/v16.6.1/lib/node_modules/generator-jhipster-kotlin/node_modules/yeoman-generator/lib/index.js:1025:11)

## Motivation for or Use Case

I am big fan of kotlin over java and want to use spring-native features.

## Reproduce the error

jhipster-native --blueprints kotlin --cache-provider no --no-enable-hibernate-cache

## KHipster Version(s)

Jhipster 7.7.0

-   [] Checking this box is mandatory (this is just to show you read everything)

**Comment by sendilkumarn** [comment]
@bahag-chaurasiak I don't think we support v7.7.0 yet. Closing this for now, but if you are interested happy to accept a PR.
