### ISSUE TITLE
registerPage.replaceAll is not a function

### ISSUE THREAD

**Issue by Digital-Nomad** [jhipster/jhipster-kotlin#327]
Running into the following error when trying to generator khipster project:

```
WARNING! /usr/local/lib/node_modules/generator-jhipster-kotlin/node_modules/generator-jhipster/generators/cypress/templates/src/test/javascript/cypress/integration/account/register-page.spec.ts.ejs
ERROR! /usr/local/lib/node_modules/generator-jhipster-kotlin/node_modules/generator-jhipster/generators/cypress/templates/src/test/javascript/cypress/integration/account/register-page.spec.ts.ejs:42
    40|     cy.visit('');
    41|     cy.clickOnRegisterItem();
 >> 42|     cy.url().should('match', /<%= registerPage.replaceAll('/', '\\/') %>$/);
    43|   });
    44| 
    45|   it('should load the register page', () => {

registerPage.replaceAll is not a function
TypeError: /usr/local/lib/node_modules/generator-jhipster-kotlin/node_modules/generator-jhipster/generators/cypress/templates/src/test/javascript/cypress/integration/account/register-page.spec.ts.ejs:42
    40|     cy.visit('');
    41|     cy.clickOnRegisterItem();
 >> 42|     cy.url().should('match', /<%= registerPage.replaceAll('/', '\\/') %>$/);
    43|   });
    44| 
    45|   it('should load the register page', () => {

registerPage.replaceAll is not a function
    at module.exports.eval (eval at compile (/usr/local/lib/node_modules/generator-jhipster-kotlin/node_modules/ejs/lib/ejs.js:662:12), <anonymous>:22:39)
    at register-page.spec.ts (/usr/local/lib/node_modules/generator-jhipster-kotlin/node_modules/ejs/lib/ejs.js:692:17)
    at /usr/local/lib/node_modules/generator-jhipster-kotlin/node_modules/ejs/lib/ejs.js:258:40
    at new Promise (<anonymous>)
    at tryHandleCache (/usr/local/lib/node_modules/generator-jhipster-kotlin/node_modules/ejs/lib/ejs.js:256:14)
    at Object.exports.renderFile (/usr/local/lib/node_modules/generator-jhipster-kotlin/node_modules/ejs/lib/ejs.js:489:10)
    at Object.renderContent (/usr/local/lib/node_modules/generator-jhipster-kotlin/node_modules/generator-jhipster/generators/utils.js:305:23)
    at module.exports.template (/usr/local/lib/node_modules/generator-jhipster-kotlin/node_modules/generator-jhipster/generators/generator-base-private.js:738:8)
    at /usr/local/lib/node_modules/generator-jhipster-kotlin/node_modules/generator-jhipster/generators/generator-base.js:2268:47
    at Array.map (<anonymous>) {
  path: '/usr/local/lib/node_modules/generator-jhipster-kotlin/node_modules/generator-jhipster/generators/cypress/templates/src/test/javascript/cypress/integration/account/register-page.spec.ts.ejs'
}

```

Running Mac monterey 12.2.1 on an intel mac with the latest version of jhipster(7.70) and yeoman.

**Comment by mraible** [comment]
Can you try with Node 16 and see if that fixes the problem?

**Comment by sendilkumarn** [comment]
@Digital-Nomad  Yeah it looks like Node version issue. Closing this for now, please feel free to reopen.
