### ISSUE TITLE
Error running generator app: SyntaxError: Missing catch or finally after try while compiling ejs

### ISSUE THREAD

**Issue by egvimo** [jhipster/jhipster-kotlin#357]
## Overview of the issue

Error generating app, when an Entity has an `@Id` String field (see JDL example below).

<details>
  <summary>Error</summary>
  
    ✖ An error occured while running jhipster:bootstrap#commitFiles
    Error running generator app: SyntaxError: Missing catch or finally after try while compiling ejs

    If the above error is not helpful, you may want to try EJS-Lint:
    https://github.com/RyanZim/EJS-Lint
    Or, if you meant to create an async function, pass `async: true` as an option.
    SyntaxError: Missing catch or finally after try while compiling ejs

    If the above error is not helpful, you may want to try EJS-Lint:
    https://github.com/RyanZim/EJS-Lint
    Or, if you meant to create an async function, pass `async: true` as an option.
        at new Function (<anonymous>)
        at Template.compile (C:\...\nodejs\v16.13.1\node_modules\generator-jhipster-kotlin\node_modules\ejs\lib\ejs.js:673:12)
        at Object.compile (C:\...\nodejs\v16.13.1\node_modules\generator-jhipster-kotlin\node_modules\ejs\lib\ejs.js:398:16)
        at TemplateFile.compile (C:\...\nodejs\v16.13.1\node_modules\generator-jhipster-kotlin\node_modules\generator-jhipster\utils\multi-step-transform\template-file.js:43:26)
        at TemplateFileFs.add (C:\...\nodejs\v16.13.1\node_modules\generator-jhipster-kotlin\node_modules\generator-jhipster\utils\multi-step-transform\template-file-fs.js:31:18)
        at MultiStepTransform.queuedTransform (C:\...\nodejs\v16.13.1\node_modules\generator-jhipster-kotlin\node_modules\generator-jhipster\utils\multi-step-transform\index.js:21:50)
        at C:\...\nodejs\v16.13.1\node_modules\generator-jhipster-kotlin\node_modules\p-transform\index.js:100:31   
        at run (C:\...\nodejs\v16.13.1\node_modules\generator-jhipster-kotlin\node_modules\p-queue\dist\index.js:157:104)
        at PQueue._tryToStartAnother (C:\...\nodejs\v16.13.1\node_modules\generator-jhipster-kotlin\node_modules\p-queue\dist\index.js:105:17)
        at C:\...\nodejs\v16.13.1\node_modules\generator-jhipster-kotlin\node_modules\p-queue\dist\index.js:171:18  
    ERROR! Missing catch or finally after try while compiling ejs

    If the above error is not helpful, you may want to try EJS-Lint:
    https://github.com/RyanZim/EJS-Lint
    Or, if you meant to create an async function, pass `async: true` as an option.
    SyntaxError: Missing catch or finally after try while compiling ejs

    If the above error is not helpful, you may want to try EJS-Lint:
    https://github.com/RyanZim/EJS-Lint
    Or, if you meant to create an async function, pass `async: true` as an option.
        at new Function (<anonymous>)
        at Template.compile (C:\...\nodejs\v16.13.1\node_modules\generator-jhipster-kotlin\node_modules\ejs\lib\ejs.js:673:12)
        at Object.compile (C:\...\nodejs\v16.13.1\node_modules\generator-jhipster-kotlin\node_modules\ejs\lib\ejs.js:398:16)
        at TemplateFile.compile (C:\...\nodejs\v16.13.1\node_modules\generator-jhipster-kotlin\node_modules\generator-jhipster\utils\multi-step-transform\template-file.js:43:26)
        at TemplateFileFs.add (C:\...\nodejs\v16.13.1\node_modules\generator-jhipster-kotlin\node_modules\generator-jhipster\utils\multi-step-transform\template-file-fs.js:31:18)
        at MultiStepTransform.queuedTransform (C:\...\nodejs\v16.13.1\node_modules\generator-jhipster-kotlin\node_modules\generator-jhipster\utils\multi-step-transform\index.js:21:50)
        at C:\...\nodejs\v16.13.1\node_modules\generator-jhipster-kotlin\node_modules\p-transform\index.js:100:31   
        at run (C:\...\nodejs\v16.13.1\node_modules\generator-jhipster-kotlin\node_modules\p-queue\dist\index.js:157:104)
        at PQueue._tryToStartAnother (C:\...\nodejs\v16.13.1\node_modules\generator-jhipster-kotlin\node_modules\p-queue\dist\index.js:105:17)
        at C:\...\nodejs\v16.13.1\node_modules\generator-jhipster-kotlin\node_modules\p-queue\dist\index.js:171:18  

</details>

## Reproduce the error

JDL:

```jdl
application {
    config {
    baseName sample
    packageName sample
    applicationType microservice
    authenticationType oauth2
    serverPort 8081
    buildTool gradle
    cacheProvider no
    clientFramework no
    databaseType sql
    prodDatabaseType postgresql
    devDatabaseType postgresql
    serviceDiscoveryType no
    enableTranslation false
    messageBroker kafka
    skipClient true
    skipUserManagement true
  }
  entities *
}

entity Abc0 {
    @Id key String
    otherField String
}
```

Generated with: `khipster import-jdl app.jdl --with-entities --skip-git --skip-install --force`

## KHipster Version(s)

1.16.0

-   [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by egvimo** [comment]
Any news on that? We are currently a little blocked by this issue. 😞

**Comment by egvimo** [comment]
The generator also fails using `id UUID`.
